### ISSUE TITLE
Library breaks AppCompat font loading

### ISSUE THREAD

**Issue by matejdro** [android/android-ktx#365]
When this library is loaded, using `android:fontFamily` attribute on any AppCompat TextViews causes app to crash with following exception:

```
java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.matejdro.testproject-1/base.apk)
	at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
	at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
	at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
	at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:67)
	at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:753)
	at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
	at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
	at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:621)
	at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:631)
	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.matejdro.testproject.MainActivity.onCreate(MainActivity.kt:10)
	at android.app.Activity.performCreate(Activity.java:6662)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

Steps to reproduce: 

1. Create new empty project in Android Studio with Kotlin support and empty AppCompat activity
2. Add KTX to classpath (`implementation 'androidx.core:core-ktx:0.1'`)
3. Add `android:fontFamily="sans-serif"` property to generated Hello World TextView.
4. Run application

**Comment by JakeWharton** [comment]
You have different versions of various support libraries on the classpath. This is not supported. [Use a Gradle resolutionStrategy to force them all to the same version.][1]

 [1]: https://github.com/JakeWharton/u2020/blob/af670f964a4750707d98cda31cfa95244eb3ec07/build.gradle#L105-L113

**Comment by luaz** [comment]
If you are using Android Studio 3.1 (Android SDK Build Tools version 27.0.3 is the minimum supported version for Android Gradle Plugin 3.1.0), you probably need
- Android Support Library: 27.0.3
- buildToolsVersion "27.0.3"
- compileSdkVersion/targetSdkVersion 27

Else, probably just making sure your Android Support Library + buildToolsVersion + compileSdkVersion/targetSdkVersion is the same to avoid this problem.

https://code.luasoftware.com/tutorials/android/no-static-method-get-font/
